# This file was generated by GoReleaser. DO NOT EDIT.
cask "yore" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "eeb9e85b694a989fbc80425bcbe94eba9c2cdfcc261c080cc49fa31d0dee3465"
      url "https://github.com/Dev-Bilaspure/yore/releases/download/v#{version}/yore_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "59892d3e655c23c4d584c39449668a167af0c3e5f4b2b93b42680ca77d713064"
      url "https://github.com/Dev-Bilaspure/yore/releases/download/v#{version}/yore_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8fb23e6645c227b463dc60389b594da48ba8a80432d8e9e4f1e4166cbbef5c41"
      url "https://github.com/Dev-Bilaspure/yore/releases/download/v#{version}/yore_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "841967b032b1bdea4e4f82c4ff1f75f936c6604b423834efc4f5d385df56781b"
      url "https://github.com/Dev-Bilaspure/yore/releases/download/v#{version}/yore_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yore"
  desc "Clean, deduplicated, frecency-ranked shell history"
  homepage "https://github.com/Dev-Bilaspure/yore"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "fzf",
    ]

  binary "yore"
  manpage "man/yore.1"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yore"] if OS.mac?
  end
  generate_completions_from_executable "yore", "completion"

  # No zap stanza required

  caveats <<~EOS
    Shell completions for bash, zsh and fish were installed.

    Enable command recording (captures cwd + exit status, unlocks `yore here`
    and binds Ctrl-G to the fuzzy picker). Add to your shell rc:

      zsh:   eval "$(yore init zsh)"      # ~/.zshrc
      bash:  eval "$(yore init bash)"     # ~/.bashrc
      fish:  yore init fish | source      # ~/.config/fish/config.fish

    Then seed it from your existing history:  yore import
  EOS
end
