# This file was generated by GoReleaser. DO NOT EDIT.
cask "yore" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "e6ce57603ca799f903504e5e27c6d3b9bafe2282ec313c4d04e6f282bdb0db65"
      url "https://github.com/Dev-Bilaspure/yore/releases/download/v#{version}/yore_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d4a8e138b83d0150d186d96017ed216c5aa3eb0d0ca2090231cd052500dfad2b"
      url "https://github.com/Dev-Bilaspure/yore/releases/download/v#{version}/yore_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cc88d55e8e3054c670dd7d5330eea6443cbf3856795fc47c678da5ddc7821058"
      url "https://github.com/Dev-Bilaspure/yore/releases/download/v#{version}/yore_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1d26005060e32e3881b1328751566f1fa46c9f959f94ed0e2f3fc694f07b1070"
      url "https://github.com/Dev-Bilaspure/yore/releases/download/v#{version}/yore_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yore"
  desc "Clean, deduplicated, frecency-ranked shell history"
  homepage "https://github.com/Dev-Bilaspure/yore"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "fzf",
    ]

  binary "yore"
  manpage "man/yore.1"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yore"] if OS.mac?
  end
  generate_completions_from_executable "yore", "completion"

  # No zap stanza required

  caveats <<~EOS
    Shell completions for bash, zsh and fish were installed.

    Enable command recording (captures cwd + exit status, unlocks `yore here`
    and binds Ctrl-G to the fuzzy picker). Add to your shell rc:

      zsh:   eval "$(yore init zsh)"      # ~/.zshrc
      bash:  eval "$(yore init bash)"     # ~/.bashrc
      fish:  yore init fish | source      # ~/.config/fish/config.fish

    Then run `yore` — it'll guide you from there.
  EOS
end
