# This file was generated by GoReleaser. DO NOT EDIT.
cask "yore" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "7070fc52034341a9a3e5cd70b43860162b2968120be1dc09386e40113c84754e"
      url "https://github.com/Dev-Bilaspure/yore/releases/download/v#{version}/yore_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9af61401e104782bf8e51d0b4884f3be77e760f495ae27be781fc11c48357821"
      url "https://github.com/Dev-Bilaspure/yore/releases/download/v#{version}/yore_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "540b706ca074b740c846f72603b322717266c2b1404ad76058755c3bdbbb4bf1"
      url "https://github.com/Dev-Bilaspure/yore/releases/download/v#{version}/yore_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "77dd2fe577a731ab320885def7ac5ba53270a8cde2305db16076f3f864f7e5c6"
      url "https://github.com/Dev-Bilaspure/yore/releases/download/v#{version}/yore_#{version}_linux_arm64.tar.gz"
    end
  end

  name "yore"
  desc "Clean, deduplicated, frecency-ranked shell history"
  homepage "https://github.com/Dev-Bilaspure/yore"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "yore"
  manpage "man/yore.1"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/yore"] if OS.mac?
  end
  generate_completions_from_executable "yore", "completion"

  # No zap stanza required

  caveats <<~EOS
    Shell completions for bash, zsh and fish were installed.

    Enable command recording (captures cwd + exit status, unlocks `yore here`
    and binds Ctrl-G to the fuzzy picker). Add to your shell rc:

      zsh:   eval "$(yore init zsh)"      # ~/.zshrc
      bash:  eval "$(yore init bash)"     # ~/.bashrc
      fish:  yore init fish | source      # ~/.config/fish/config.fish

    Then seed it from your existing history:  yore import
  EOS
end
